#ifndef HEADER_SMPC_BYTECODE_H
#define HEADER_SMPC_BYTECODE_H

/* BYTECODE TYPE */
#define SMP_BYTE unsigned char
#define SMP_BYTE_SIZE 256

/* BYTECODE INSTRUCTIONS */
#define SMP_STORE 0b1
#define SMP_EXIT 0b10
#define SMP_PRINT 0b11

#endif /* HEADER_SMPC_BYTECODE_H */
